### ISSUE TITLE
The release of the training code

### ISSUE THREAD

**Issue by bityigoss** [NVlabs/Minitron#5]
Hi, thanks for your great work.
I'm interested in the knowledge distillation part, will you open source the training code?

**Comment by srvm** [comment]
Hi, thank you for the question. We do have plans to open-source the distillation code, but the timeline is still a bit unclear. We are currently working on getting approvals ready, stay tuned!

**Comment by srvm** [comment]
Closing.

**Comment by bityigoss** [comment]
@srvm sorry, is there any progress?
