### ISSUE TITLE
Llama-3.1-Minitron-4B-Width-Base repo is not found.

### ISSUE THREAD

**Issue by atyenoria** [NVlabs/Minitron#6]
Is there any reason why https://huggingface.co/nvidia/Llama-3.1-Minitron-4B-Width-Base doesn't exist? 
I wanted to finetune it.

**Comment by srvm** [comment]
Hi, the checkpoint is now live. Apologies for the delay.
https://huggingface.co/nvidia/Llama-3.1-Minitron-4B-Width-Base

**Comment by atyenoria** [comment]
Thanks for creating!
