### ISSUE TITLE
Question for insight in the paper LLM Pruning and Distillation in Practice: The Minitron Approach

### ISSUE THREAD

**Issue by Leun9** [NVlabs/Minitron#8]
Insights.General.3
For width pruning, we achieve stronger accuracy by retaining attention heads and pruning the other dimensions (MLP intermediate dimension, embedding channels).

Do you have any experimental data to support this conclusion?

**Comment by srvm** [comment]
We don't have a separate ablation for this in the paper, but just to expand on this a bit: we performed lightweight fine-tuning (see Section 2.3 of the original Minitron paper [1] for more details on this) of a few (<10) width-pruned candidates that used different ratios of attention, MLP and emb widths, and found that candidates that retained all the original attention heads performed slightly better than ones that had pruned heads.

It is also worth noting that these models were optimized purely for accuracy: when trying to optimize for a combination of latency and accuracy, it's very likely that the search algorithm will prefer reducing nheads and depth over other axes.

References:
1. [Compact language models via pruning and knowledge distillation](https://arxiv.org/abs/2407.14679)
