### ISSUE TITLE
Release of Curated Dataset Used in Knowledge Distillation

### ISSUE THREAD

**Issue by zolastro** [NVlabs/Minitron#9]
Hi,

I was wondering if there are any plans to release the curated dataset that was used for retraining the teacher model and performing knowledge distillation. Sharing this dataset would significantly enhance reproducibility and facilitate fair comparisons between different methods.

Thanks!

**Comment by srvm** [comment]
Hi,

The dataset we use for distillation is part of the larger Nemotron-4 dataset [1], as noted in the paper. We don't currently have any plans to open-source this dataset, unfortunately.

That said, there are a number of high-quality, curated and open datasets that you could alternatively use with our pruning recipe (which should continue to work well with other datasets). A good example is the SmolLM corpus: https://huggingface.co/datasets/HuggingFaceTB/smollm-corpus

References:
1. https://arxiv.org/abs/2406.11704
